#if GAME_LANGUAGE == LANGUAGE_SPANISH

gText_Birch_Welcome:: @ 82C897B
	.string "¡Hola! Perdona que te haya\n"
	.string "hecho esperar.\p"
	.string "¡Te doy la bienvenida al fabuloso\n"
	.string "mundo de los Pokémon!\p"
	.string "Me llamo Abedul.\p"
	.string "Pero todo el mundo me llama\n"
	.string "Profesor Abedul.\p"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "El mundo está habitado por\n"
	.string "criaturas llamadas Pokémon.\p"
	.string "Los humanos y los Pokémon vivimos\n"
	.string "juntos. A veces nos lo pasamos bien\l"
	.string "y nos ayudamos unos a otros.\p"
	.string "A veces nos unimos y combatimos\n"
	.string "contra equipos como el nuestro.\p"
	.string "Pero, a pesar de estos vínculos,\n"
	.string "ignoramos mucho sobre los Pokémon.\p"
	.string "De hecho, hay multitud de secretos\n"
	.string "que rodean a los Pokémon.\p"
	.string "En mi afán por descubrirlos, he\n"
	.string "dedicado mi vida a la investigación.\l"
	.string "Eso es lo que hago.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "¿Tú quién eres?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "¿Eres un chico o una chica?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "Muy bien.\n"
	.string "¿Y cómo te llamas?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "Así que eres {PLAYER}…$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "¡Ah, sí, ya me acuerdo!\p"
	.string "Tú te acabas de mudar a mi\n"
	.string "pueblo natal, Villa Raíz.\l"
	.string "¿A que sí?\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "Vale, escucha bien lo que te\n"
	.string "voy a decir…\p"
	.string "Tu propia aventura está a punto\n"
	.string "de comenzar.\p"
	.string "Adelante, entra en el mundo de los\n"
	.string "Pokémon: un mundo de ensueño, lleno\l"
	.string "de aventuras y grandes amigos.\p"
	.string "Bueno, ven a verme luego. Te espero\n"
	.string "en mi Laboratorio Pokémon.\p"
	.string "$"

#else

gText_Birch_Welcome:: @ 82C897B
	.string "Bismillah! Terima kasih sudah menunggu. Mari kita mulai!\p"
	.string "Selamat datang ke Pokémon R.O.W.E!\p"
	.string "Hoenn Edisi Ramadan bisa kamu jelajahi\n"
	.string "secara bebas!\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "“Pokémon.” adalah makhluk yang seperti ini\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "Ratusan spesies makhluk serupa sudah teridentifikasi\n"
	.string "sebagai Pokémon oleh para ilmuwan.\p"
	.string "Pokémon dan manusia hidup berdampingan,\n"
	.string "kita banyak belajar dari mereka, dan\l"
	.string "semua itu adalah suatu anugrah dari yang Maha Kuasa.\p"
	.string "Beradu Pokémon bukanlah sekedar hobi saja,\n"
	.string "tapi juga sebagai ikhtiar mencari jati diri.\p"
	.string "Yakinlah, Allah Maha Memiliki Ilmu,\n"
	.string "sementara pengetahuan manusia sangatlah terbatas.\p"
	.string "Adakah hikmah rahasia dalam spesies Pokémon,\n"
	.string "bisakah kita memahaminya?\p"
	.string "Bulan Ramadan ini,\n"
	.string "Saya mendapat inpirasi.\l"
	.string "Mencari korelasi antara Muslim & Pokémon.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "Siapa namamu?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "kamu ikhwan?\n"
	.string "ataukah akhwat?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "Baiklah.\n"
	.string "Siapa nama engkau?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "{PLAYER}{KUN} rupanya?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Oh, oke-oke!\p"
	.string "Salam {PLAYER}{KUN}\n"
	.string "Saya kini tahu!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "Oke, sekarang, siapkah kamu?\p"
	.string "Dunia Pokémon yang fana\n"
	.string "akan segera kamu hadapi!\p"
	.string "Pilih kota pertamamu dan jelajahi Hoenn,\n"
	.string "namun jangan lupakan dunia akhirat.\l"
	.string "Petualangan di Hoenn dijamin seru!\p"
	.string "Tapi INGAT! malaikat mencatat disisi kita,\n"
	.string "Mainkan game ini secara bijak!\l"
	.string "BISMILLAH.$"

#endif
