Text_PictureBookShelf: @ 82A81E5
	.string "Panduan Tajwid Qur'an edisi Pokémon Mengaji, 1445.$"

Text_BookShelf: @ 82A820D
	.string "Banyak sekali buku-buku kurikulum santri pesantren.$"

Text_PokemonCenterBookShelf: @ 82A8232
	.string "Pokémon dan Kecerdasan Buatan!\n"
	.string "Hikmah Bermain Pokémon\p"
	.string "Fa Kaf Mim Nun\n"
	.string "Alif Lam Ro…$"

Text_Vase: @ 82A8276
	.string "Vas keramik produksi UMKM Jogja…\n"
	.string "Coba intip isinya…\p"
	.string "Tuh kan, Kosong.$"

Text_EmptyTrashCan: @ 82A82B3
	.string "Kosong, berdebu.$"

Text_ShopShelf: @ 82A82BF
	.string "Rak penuh sesak buku berbagai topik\n"
	.string "juga seperangkat alat sholat.$"

Text_Blueprint: @ 82A82F7
	.string "Ini artikel jurnal ilmiah?\n"
	.string "Terkait tafsir Qur'an. Ah, rumitnya!$"
