gText_FlyingTaxi_Intro::
    .string "Assalamualaikum, ini jasa Taksi Terbang\n"
    .string "Kakak mau diantar? Bukan naik Buraq.\p"
    .string "Tapi ngaji bareng dulu Surat Al-Isra.$"

gText_FlyingTaxi_WhereDoYouWantToGo::
    .string "Jadi kakak tujuannya ke mana?$"

gText_FlyingTaxi_Goodbye::
    .string "Jangan ragu pakai jasa kami di kesempatan berikutnya.\n"
    .string "Selalu ada jalan menghafal Al-Isra!$"
	
//Gym Items
	Special_Gym_Text_Explain_Amulet_Coin:
	.string "Ini namanya Amulet Coin\p"
	.string "Pokémon pertama dalam rombongan kamu\n"
	.string "jika mengenakan benda ini.\p"
	.string "Akan ditandai sebagai kaum dhuafa,\n"
	.string "sehingga berhak dapat banyak infaq.$"
	
	Special_Gym_Text_Explain_Item_Finder:
	.string "Ini namanya Item Finder.\p"
	.string "Kamu akan mudah untuk menemukan benda ghoib\n"
	.string "tersembunyi, jika memakai benda ini.$"
	
	Special_Gym_Text_Explain_Good_Rod:
	.string "Ini kail pancing tipe Good Rod.\n"
	.string "Spesies lebih kuat akan bisa ter-\l"
	.string "tangkap oleh kail ini.$"
	
	Special_Gym_Text_Explain_Oval_Charm:
	.string "This item is an Oval Charm.\p"
	.string "Its an item that doubles the\n"
	.string "possibilites of getting an Baby\l"
	.string "Pokémon from the Daycare.$"

	Special_Gym_Text_Explain_Catching_Charm:
	.string "This item is a Catching Charm.\p"
	.string "It increase the chance of getting a\n"
	.string "critical catch.$"
	
	Special_Gym_Text_Explain_Super_Rod:
	.string "This item is the Super Rod.\p"
	.string "Its the ultimate Rod you can find,\n"
	.string "its used by the pros for catching\l"
	.string "the strongest water Pokémon.$"
	
	Special_Gym_Text_Explain_Lucky_Egg:
	.string "This item is a Lucky Egg.\p"
	.string "Make your Pokémon Hold it\n"
	.string "and it will gain double the Exp.$"
	
	Special_Gym_Text_Explain_Mega_Bracelet:
	.string "This item is the Mega Bracelet.\p"
	.string "This item will make you able\n"
	.string "to Mega Evolve your Pokémon\p"
	.string "Pressing Start with a Pokémon\n"
	.string "that can Mega Evolve in Battle.$"
	
	Special_Gym_Text_Explain_Shiny_Charm:
	.string "This item is the Shiny Charm.\p"
	.string "Its an item that doubles the\n"
	.string "possibilites of getting a shiny\l"
	.string "Pokémon.$"
	
	Special_Gym_Text_Explain_Old_Save:
	.string "It looks like you are using\n"
	.string "an old Save File.\p"
	.string "I need to update your Items and\n"
	.string "some other things before you can\l"
	.string "continue.$"
